name: Render README and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'README.md'
      - '.github/workflows/**'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write       # Needed to commit the rendered file
  pages: write          # Needed to deploy GitHub Pages
  id-token: write       # Needed for GitHub Pages OIDC auth

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Render README.md to HTML using GitHub Markdown API (structured)
        run: |
          MARKDOWN_TEXT=$(jq -Rs . < README.md)

          RESPONSE=$(curl -w "%{http_code}" -o docs/rendered_readme.html \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/markdown \
            -d "{\"text\": $MARKDOWN_TEXT, \"mode\": \"gfm\", \"context\": \"${{ github.repository }}\"}")

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Failed to render markdown. HTTP status code: $RESPONSE"
            exit 1
          fi

      - name: Commit rendered HTML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/rendered_readme.html
          git diff --cached --quiet || git commit -m "Update rendered README [skip ci]"
          git push

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
